import { styled } from '@stitches/react';
import Image from 'next/image';
import defaultAvatar from '../../assets/default-avatar-300x300.png';
import * as CollapsiblePrimitive from '@radix-ui/react-collapsible';
import { useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faAngleDown,
  faCirclePlus,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';
import { Button } from '../../components/Button';
import { useForm } from 'react-hook-form';
import Head from 'next/head';

const Avatar = styled(Image, {
  borderRadius: '50%',
});

const Header = styled('header', {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'space-between',
  padding: '12px',
  boxShadow: '0 0 1px rgba(0, 0, 0, 0.4)',
});

const MainContainer = styled('main', {
  display: 'grid',
  gridTemplateColumns: '250px 1fr',
  height: '100%',
});

const LateralMenuContainer = styled('div', {
  display: 'flex',
  flexDirection: 'column',
  height: '100%',
  padding: '12px',
});

const ContentContainer = styled('div', {
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
  backgroundColor: '#3fb0ac',
  width: '100%',
  height: '100%',
});

const Flex = styled('div', { display: 'flex' });

const CollapsibleContent = styled(CollapsiblePrimitive.CollapsibleContent, {
  overflow: 'hidden',
});

const Main = () => {
  const [open, setOpen] = useState(false);
  const [projects, setProjects] = useState([
    'Projeto 1',
    'Projeto 2',
    'Projeto 3',
  ]);
  const [tasks, setTasks] = useState([
    {
      id: 1,
      content: 'dasdasd',
    },
  ]);

  const defaultValues = {} as any;

  tasks.forEach((task) => {
    defaultValues['input-' + task.id] = task.content;
  });

  const { register, handleSubmit } = useForm({ defaultValues });

  const removeTask = (i: number) => {
    setTasks(tasks.filter((task, index) => index != i));
  };

  const newTask = () => {
    setTasks([...tasks, { id: tasks.length + 1, content: '' }]);
  };

  const onSubmitForm = (data: any) => {
    console.log(data);
  };

  return (
    <>
      <Head>
        <title>Ledes Weekly Report</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <div>
          <h1>Ledes Weekly Report</h1>
        </div>
        <Avatar src={defaultAvatar} width={48} height={48} />
      </Header>
      <MainContainer>
        <LateralMenuContainer>
          <CollapsiblePrimitive.Collapsible open={open} onOpenChange={setOpen}>
            <Flex css={{ alignItems: 'center', justifyContent: 'center' }}>
              <CollapsiblePrimitive.CollapsibleTrigger asChild>
                <div>
                  <FontAwesomeIcon
                    color="#3fb0ac"
                    icon={faAngleDown}
                    style={{ marginRight: '12px' }}
                  />
                </div>
              </CollapsiblePrimitive.CollapsibleTrigger>
              <span>Projetos Associados</span>
            </Flex>

            <CollapsibleContent>
              <ul>
                {projects.map((project, i) => (
                  <li key={i}>{project}</li>
                ))}
              </ul>
            </CollapsibleContent>
          </CollapsiblePrimitive.Collapsible>
        </LateralMenuContainer>
        <ContentContainer>
          <form onSubmit={handleSubmit(onSubmitForm)}>
            <h1>Novo relatório</h1>

            <div>
              <label htmlFor="targetInput">Para: </label>
              <select
                name="targetInput"
                id="targetInput"
                style={{
                  border: 'none',
                  outline: 'none',
                  padding: '4px 8px',
                }}
              >
                {projects.map((project, index) => (
                  <option value={'projeto' + index}>{project}</option>
                ))}
              </select>
            </div>

            <p>Tarefas realizadas:</p>

            <Flex
              css={{
                width: '100%',
                flexDirection: 'column',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              {tasks.map((task, i) => (
                <Flex
                  css={{
                    marginBottom: '4px',
                    alignItems: 'center',
                    justifyContent: 'center',
                  }}
                  key={task.id}
                >
                  <Flex
                    css={{
                      width: '16px',
                      justifyContent: 'start',
                      color: 'black',
                    }}
                  >
                    <label htmlFor={'targetInput' + task}>{task.id}.</label>
                  </Flex>
                  <Flex
                    css={{
                      width: '825px',
                      height: '25px',
                      background: 'white',
                      alignItems: 'center',
                    }}
                  >
                    <input
                      style={{
                        width: '100%',
                        height: '100%',
                        padding: '4px 8px',
                        border: 'none',
                        outline: 'none',
                        fontSize: '16px',
                        resize: 'none',
                      }}
                      type="text"
                      {...register('input-' + task.id)}
                    />
                    <a href="#" onClick={() => removeTask(i)}>
                      <FontAwesomeIcon
                        color="#F0F0F0"
                        icon={faXmark}
                        style={{ marginRight: '12px' }}
                      />
                    </a>
                  </Flex>
                </Flex>
              ))}
              <div onClick={() => newTask()}>
                <FontAwesomeIcon
                  color="white"
                  icon={faCirclePlus}
                  style={{ marginRight: '12px' }}
                />
                iconaqui
              </div>
              <Button
                type="submit"
                css={{
                  fontSize: '18px',
                  fontWeight: 300,
                  width: '300px',
                }}
              >
                Submeter
              </Button>
            </Flex>
          </form>
        </ContentContainer>
      </MainContainer>
    </>
  );
};

export default Main;
